# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f7ab5e57770f0892dcf565f50fda3a67fd2cbb82865b43f61bf7b6b953e7c985278ccec213a58c9756ff575586da13110e0eafde2f9894fb47e87cb6321d77b

test:
  secret_key_base: 22bafba198f3139da5f04b42b414d7071d4f4ae4644b2886124b115e7671029e8ec2ea69c9cd783ad7d5118dda758b972c9c18d35588d97d2f1b0b9a660f8a11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
